{
 "title": "Experiments",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Workqueue Wait Times for VirtualNetworks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(workqueue_queue_duration_seconds_sum{job=\"crossplane-provider-tf-azure\",name=\"managed/virtual.azure.tf.crossplane.io/v1alpha1, kind=virtualnetwork\"}[5m]) / rate(workqueue_queue_duration_seconds_count{job=\"crossplane-provider-tf-azure\",name=\"managed/virtual.azure.tf.crossplane.io/v1alpha1, kind=virtualnetwork\"}[5m])",
     "legendFormat": "VirtualNetwork Average  5 min"
    },
    {
     "expr": "rate(workqueue_queue_duration_seconds_sum{job=\"crossplane-provider-tf-azure\",name=\"managed/lb.azure.tf.crossplane.io/v1alpha1, kind=lb\"}[5m]) / rate(workqueue_queue_duration_seconds_count{job=\"crossplane-provider-tf-azure\",name=\"managed/lb.azure.tf.crossplane.io/v1alpha1, kind=lb\"}[5m])",
     "legendFormat": "Lb Average  5 min"
    }
   ]
  },
  {
   "title": "Workqueue Wait Times for VirtualNetworks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(workqueue_queue_duration_seconds_bucket{job=\"crossplane-provider-tf-azure\",name=\"managed/virtual.azure.tf.crossplane.io/v1alpha1, kind=virtualnetwork\"}[5m]))",
     "legendFormat": "p99 5 min"
    },
    {
     "expr": "histogram_quantile(0.50, rate(workqueue_queue_duration_seconds_bucket{job=\"crossplane-provider-tf-azure\",name=\"managed/virtual.azure.tf.crossplane.io/v1alpha1, kind=virtualnetwork\"}[5m]))",
     "legendFormat": "Median"
    },
    {
     "expr": "rate(workqueue_queue_duration_seconds_sum{job=\"crossplane-provider-tf-azure\",name=\"managed/virtual.azure.tf.crossplane.io/v1alpha1, kind=virtualnetwork\"}[5m]) / rate(workqueue_queue_duration_seconds_count{job=\"crossplane-provider-tf-azure\",name=\"managed/virtual.azure.tf.crossplane.io/v1alpha1, kind=virtualnetwork\"}[5m])",
     "legendFormat": "Average  5 min"
    }
   ]
  },
  {
   "title": "Workqueue 5 min Arrival Rate for VirtualNetworks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "arrivals/s" } },
   "targets": [
    {
     "expr": "rate(workqueue_adds_total{job=\"crossplane-provider-tf-azure\", name=\"managed/virtual.azure.tf.crossplane.io/v1alpha1, kind=virtualnetwork\"}[5m])",
     "legendFormat": "Arrival rate"
    }
   ]
  },
  {
   "title": "Workqueue Depths for Azure Objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "workqueue_depth{job=\"crossplane-provider-tf-azure\", name=\"managed/virtual.azure.tf.crossplane.io/v1alpha1, kind=virtualnetwork\"}",
     "legendFormat": "VirtualNetwork"
    },
    {
     "expr": "workqueue_depth{job=\"crossplane-provider-tf-azure\", name=\"managed/lb.azure.tf.crossplane.io/v1alpha1, kind=lb\"}",
     "legendFormat": "LoadBalancer"
    },
    {
     "expr": "workqueue_depth{job=\"crossplane-provider-tf-azure\", name=\"managed/lb.azure.tf.crossplane.io/v1alpha1, kind=lb\"} + ignoring(name) workqueue_depth{job=\"crossplane-provider-tf-azure\", name=\"managed/virtual.azure.tf.crossplane.io/v1alpha1, kind=virtualnetwork\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Number of Azure Objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "etcd_object_counts{resource=\"virtualnetworks.virtual.azure.tf.crossplane.io\"}",
     "legendFormat": "VirtualNetworks"
    },
    {
     "expr": "etcd_object_counts{resource=\"lbs.lb.azure.tf.crossplane.io\"}",
     "legendFormat": "LoadBalancers"
    },
    {
     "expr": "etcd_object_counts{resource=\"lbs.lb.azure.tf.crossplane.io\"} + ignoring(resource) etcd_object_counts{resource=\"virtualnetworks.virtual.azure.tf.crossplane.io\"}",
     "legendFormat": "Total Azure Objects"
    }
   ]
  },
  {
   "title": "Response Latencies for Azure VirtualNetworks",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 15, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, verb, subresource) (rate(apiserver_request_duration_seconds_bucket{group=\"virtual.azure.tf.crossplane.io\", resource=\"virtualnetworks\", verb!=\"WATCH\"}[5m])))",
     "legendFormat": "p99 5 min {{verb}} {{subresource}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le, verb, subresource) (rate(apiserver_request_duration_seconds_bucket{group=\"virtual.azure.tf.crossplane.io\", resource=\"virtualnetworks\", verb!=\"WATCH\"}[5m])))",
     "legendFormat": "Median 5 min {{verb}} {{subresource}}"
    },
    {
     "expr": "rate(apiserver_request_duration_seconds_sum{group=\"virtual.azure.tf.crossplane.io\", resource=\"virtualnetworks\", verb!=\"WATCH\"}[5m]) / rate(apiserver_request_duration_seconds_count{group=\"virtual.azure.tf.crossplane.io\", resource=\"virtualnetworks\", verb!=\"WATCH\"}[5m])",
     "legendFormat": "Avg. 5 min {{verb}} {{subresource}}"
    }
   ]
  },
  {
   "title": "CPU & Memory Utilization for provider-tf-azure node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "instance:node_cpu_utilisation:rate5m{instance=\"10.142.15.192:9100\"} * 100",
     "legendFormat": "5 min {{instance}} cpu"
    },
    {
     "expr": "instance:node_memory_utilisation:ratio{instance=\"10.142.15.192:9100\"} * 100",
     "legendFormat": "{{instance}} mem"
    }
   ]
  },
  {
   "title": "Reconciliation Times for VirtualNetworks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(controller_runtime_reconcile_time_seconds_bucket{controller=\"managed/virtual.azure.tf.crossplane.io/v1alpha1, kind=virtualnetwork\"}[5m]))",
     "legendFormat": "p99 5 min "
    },
    {
     "expr": "histogram_quantile(0.50, rate(controller_runtime_reconcile_time_seconds_bucket{controller=\"managed/virtual.azure.tf.crossplane.io/v1alpha1, kind=virtualnetwork\"}[5m]))",
     "legendFormat": "Median 5 min"
    },
    {
     "expr": "rate(controller_runtime_reconcile_time_seconds_sum{controller=\"managed/virtual.azure.tf.crossplane.io/v1alpha1, kind=virtualnetwork\"}[5m]) / rate(controller_runtime_reconcile_time_seconds_count{controller=\"managed/virtual.azure.tf.crossplane.io/v1alpha1, kind=virtualnetwork\"}[5m])",
     "legendFormat": "5 min Average"
    }
   ]
  },
  {
   "title": "5min Reconcile Error Rate for VirtualNetworks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "errors/s" } },
   "targets": [
    {
     "expr": "rate(controller_runtime_reconcile_errors_total{controller=\"managed/virtual.azure.tf.crossplane.io/v1alpha1, kind=virtualmachine\"}[5m])",
     "legendFormat": "reconcile errors"
    }
   ]
  },
  {
   "title": "Reconciliation Result Ratios for VirtualNetworks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "controller_runtime_reconcile_total{controller=\"managed/virtual.azure.tf.crossplane.io/v1alpha1, kind=virtualnetwork\"} / ignoring(result) group_left sum without(result) (controller_runtime_reconcile_total{controller=\"managed/virtual.azure.tf.crossplane.io/v1alpha1, kind=virtualnetwork\"})",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "instance:node_memory_utilisation:ratio * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "instance:node_cpu_utilisation:rate5m * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage for provider-tf-azure",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"crossplane-system\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"crossplane-system\", workload=~\".*-provider-tf-azure-.*\", workload_type=\"deployment\"}\n) by (pod)\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage of provider-tf-azure",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{namespace=\"crossplane-system\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"crossplane-system\", workload=~\".*-provider-tf-azure-.*\", workload_type=\"deployment\"}\n) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Request Rates for Azure VirtualNetworks",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 15, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{group=\"virtual.azure.tf.crossplane.io\", resource=\"virtualnetworks\"}[5m]))",
     "legendFormat": "5 min All Requests Rate"
    },
    {
     "expr": "sum(rate(apiserver_request_total{group=\"virtual.azure.tf.crossplane.io\", resource=\"virtualnetworks\",code!~\"2..\",code!=\"0\"}[5m]))",
     "legendFormat": "5 min Errored Requests Rate"
    }
   ]
  }
 ]
}